version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id

      - name: status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - completed
                  - placed
                  - shipped
                  - returned


  - name: stg_order_items
    columns:
      - name: order_item_id
        tests:
          - not_null
          - unique